"use client"

import Link from 'next/link';
import { useState } from 'react';
import {Howl, Howler} from 'howler';

//Joker script Murray scene, copied from: https://d2bu9v0mnky9ur.cloudfront.net/academy2019/screenplay/joker/joker_new_final.pdf
let textData = {
  "pages": { 
      "1": "MURRAY FRANKLIN (looking into camera): O-kay, you may have seen that clip of our next guest when we first played it a couple weeks ago. Now before he comes out, I just want to say that we're all heartbroken at what's going on in the city tonight. But, this is how he wanted to come out, and honestly I think we could all use a good laugh. So, please welcome-- Joker. \n BEHIND THE SHIMMERING MULTICOLORED CURTAIN, Joker gathers himself, ready for his moment. Doesn't hear his introduction or see a STAGEHAND pull open the curtain for him to go out-- ON SET, THE CURTAIN'S OPEN, Ellis Drane and his Jazz Orchestra are playing Joker on. He doesn't come out. Murray looks over to the empty space in the curtain. The audience laughs. BEHIND THE CURTAIN, Joker sees the stagehand motioning for him to go out on stage.",
      "2": "Joker starts out, pausing when he takes a step into the bright lights. The stagehand doesn't see him stop, and drops the curtain back on Joker before the audience can really see his face-- Tangling Joker up in the curtain. The audience keeps laughing thinking it's part of his act. The band keeps playing him on. Joker untangles himself from the curtain and the audience gets a good look at him. Some continue laughing. A few boo. Most don't know what to make of him. Joker walks across the stage, forgetting to wave like he practiced. He trips over the riser surrounding the set when he goes to shake Murray's hand. Almost falls on him. Murray tries not to crack up. The audience laughs. Thinks it's part of Joker's act. Joker reaches out to hug Dr. Sally as she goes in for a handshake. Another awkward moment. More laughs. Barry O'Donnell stands there with his hands up, as if to say what about me? Joker ignores him and just sits down next to Murray. Crosses and uncrosses his legs. Can't get comfortable. Murray shakes his head. \nMURRAY FRANKLIN: So, ahhh, thanks for coming on the show. But I gotta tell ya, with what happened at City Hall today, I'm sure many of our viewers here, and at home, might find this look of yours in poor taste. Joker's not listening to Murray. He's mesmerized by all the lights shining on him... all the eyes on him... he doesn't answer Murray. Nervous laughter from the audience. \nMURRAY FRANKLIN (tries again) So... can you tell us why you're dressed like this? A lot of protesters are going with this look, right? City seems to be full of clowns these days. A long uncomfortable beat.",
      "3": "JOKER (glances at the studio audience; awkward) Yeah. Isn't it great? INT. DIRECTOR'S BOOTH, STUDIO 4B - CONTINUOUS Dead silence in the booth, everybody's just staring at the monitors. \nTECHNICAL DIRECTOR (looks to the director) This guy's got nothing. \nDIRECTOR (hits the producer's talk button; into the mic) Gene, what the hell? You wanna kill this? INT. TALK SHOW SET, STAGE - CONTINUOUS Murray glances over at his producer Gene Ufland, who's sitting off-camera on a director's chair by a monitor. Gene shrugs at him. \nMURRAY FRANKLIN (smiles; trying to save the interview) So when we talked earlier, you mentioned that you aren't political. That this look isn't a political statement. \nJOKER That's right. I'm not political, Murray. I'm just trying to make people laugh. \nMURRAY FRANKLIN (beat; smiles) How's that goin' for ya? The studio audience laughs at Joker. Joker doesn't answer Murray, just smiles to himself. \nMURRAY FRANKLIN (trying not to laugh) Have you been working on any new material? Do you want to tell us a joke now?",
      "4": "The audience claps, egging Joker on to tell a joke. Joker reaches into his jacket pocket and-- Pulls out his worn notebook. Looks through it, sees Bruce Wayne's photo, pauses for a moment then turns the page. Finds the joke-- JOKER (reading) Okay. Here's one. Knock-knock. \nMURRAY FRANKLIN And you had to look that up? Studio audience laughs. \nJOKER (nods; reads it again) I want to get it right. Knock knock. Murray makes a face like, Okay, I’ll go along with this. \nMURRAY FRANKLIN Who’s there? Joker looks up from his notebook-- Sees the audience looking back at him, waiting for the punchline. Decides to finish the joke-- \nJOKER It's the police, ma'am. Your son has been hit by a drunk driver. He's dead. A few in the audience groan. A couple even laugh. Ellis Drane plays wha-wha-wha-whuuuuh on his trumpet from the band stand. Barry O'Donnell clears his throat. \n\n\nDR. SALLY FRIEDMAN Ahhhh! No, no,-- You can not joke about that. \n\n\nMURRAY FRANKLIN (shakes his head; irritated) Yeah, that's not funny, that's not the kind of humor we do on this show.",
      "5": "Murray glances over at Gene in the wings. He gives him the wrap it up sign. \n\n\nJOKER (just keeps going, on a roll) Sorry. It's been a rough few weeks, Murray. Ever since I killed those three Wall Street guys. Beat. Studio audience can't tell if he's joking or not. Murray can't either. \nMURRAY FRANKLIN (looks at him confused) Okay. I'm waiting for the punchline. \nJOKER There is no punchline. It's not a joke. INT. DIRECTOR'S BOOTH, STUDIO 4B - CONTINUOUS The director stares at the monitor. \nDIRECTOR Did he just confess to killing the Wall Street Three? \nTECHNICAL DIRECTOR (horrified) Yeah. I think he did. \nASSOCIATE DIRECTOR (turns to the director, nods) He definitely did. \nDIRECTOR Jesus Christ. (hits the camera talk button, into mic) Camera Three, get in close. ANGLE ON MONITOR, Camera Three slowly zooming in close on Joker's face.",
      "6": "INT. TALK SHOW SET, STAGE - CONTINUOUS Gene Ufland motions for Murray to kill the interview. Murray shakes his head to himself. This is a big get, it could be great television. \nMURRAY FRANKLIN (turns back to Joker; with gravitas) You're serious, aren't you? You're telling us you killed those three young men on the subway. Why should we believe you? \nJOKER (shrugs) I got nothing left to lose, Murray. Nothing can hurt me anymore. This is my fate, my life is nothing but a comedy. INT. SOPHIE'S APARTMENT, LIVING ROOM - CONTINUOUS Sophie's sitting on her couch watching this interview play out on TV. GiGi's asleep next to her. The open envelope and the money are lying on the coffee table. No sign of the flowers anywhere. \nMURRAY FRANKLIN (ON TV) Let me get this straight, you think killing those guys is funny? \nJOKER (ON TV) Comedy is sub, subjective, isn't that what they say? All of you, the system that knows so much, you decide what's right or wrong. What's real or what's made up. The same way you decide what's funny or not. Sophie edges forward on the couch, can almost see a hint of agreement on her face. INT. TALK SHOW SET, STAGE - STUDIO 4B - CONTINUOUS Back on set, we can tell by the way Murray's now interviewing Joker, talking to him slower, more thoughtfully, that he thinks this is gonna get him an Emmy... Maybe even a Peabody.",
      "7": "\nMURRAY FRANKLIN (beat) Okay, I think I understand. You did it to start a movement, to become a symbol. \nJOKER C'mon, Murray, do I look like the kind of clown who could start a movement? I killed those guys because they were awful. Everybody's awful these days. It's enough to make anyone crazy. \nMURRAY FRANKLIN So that's it, huh, you're crazy. That's your defense for killing three young men? Because they were mean to you? \nJOKER No. They couldn't carry a tune to save their lives. Some audible groans from the audience. \nJOKER Why is everyone so upset about these guys? Because Thomas Wayne went and cried about them on TV? \nMURRAY FRANKLIN You have a problem with Thomas Wayne, too? \nJOKER Yeah. I do. Everything comes so easy for him. \nMURRAY FRANKLIN And what's wrong with that? \nJOKER Have you seen what it's like out there, Murray? Do you ever actually leave this studio? Everybody just yells and screams at each other. Nobody's civil anymore. Nobody thinks what it's like to be the other guy. You think men like Thomas Wayne ever think what it's like to be a guy like me? To be anybody but themselves. (MORE)",
      "8": "(shaking his head, voice rising) They don't. They think we'll all just sit there and take it like good little boys. That we won't go wild. Well, this is for all of you out there. Joker howls at the moon. It's fucking weird. \nMURRAY FRANKLIN So much self-pity, Arthur. You sound like you're making excuses for killing three young men. Not everybody's awful. \nJOKER You're awful, Murray. There is no more laughter. The audience is watching this exchange with full attention. \nMURRAY FRANKLIN Me? How am I awful? \nJOKER Playing my video, inviting me on the show,-- You just wanted to make fun of me. You're just like the rest of them, Murray. Everything comes too easy for you. \nMURRAY FRANKLIN (on the spot; defensive) You don't know the first thing about me, pal. Look what happened because of what you did, what it led to. There are riots out there. Two policemen are in critical condition, someone was killed today. \nJOKER How about another joke, Murray? \nMURRAY FRANKLIN No, I think we've had enough of your jokes-- \nJOKER What do you get when you cross a mentally-ill loner with a system that abandons him and treats him like trash? ",
      "9": "JOKER (pulling the gun) I'll tell you what you get. You get what you fucking deserve,-- ",
      "10": "And as Murray Franklin turns, JOKER SHOOTS THE SIDE OF MURRAY'S HEAD OFF-- Blood splatters all over the back of the set. Some spraying in Joker's face. AUDIENCE SCREAMS! Dr. Sally dives for the floor. Barry O'Donnell reaches over her to try and save Murray--",
      "11": "JOKER looks straight into camera; screams Murray's signature sign off) GOOD NIGHT AND ALWAYS REMEMBER,-- THAT'S LIFE!"
  }
}

export default function FirstPost() {
  let [currentIndex, setIndex] = useState(1);

  return (
    <>
    <div className={"max-w-screen-lg m-auto"}>
      <div className={"mb-5"}>
        <h1 className={"text-3xl font-bold"}>Submission Point 2 - Page Viewer</h1>
        <h2>Howler.js in Next.js. Tailwind practice also included</h2>
        <Link className={"text-red-600 font-bold"} href="/">Switch to Text Editor</Link>
      </div>
      <p className='text-center'>Joker - Murray Scene</p>
      <div style={{height: "80dvh"}} className="border-solid border-black border-2">
        <div className={"flex justify-between p-6 h-full"}>
          <button className={"font-bold text-3xl"} onClick={() => setIndex(currentIndex - 1)}>{"<"}</button>
          <p className={"self-center p-6 text-lg"}>{textData.pages[currentIndex]}</p>
          <button className={"font-bold text-3xl"} onClick={() => setIndex(currentIndex + 1)}>{">"}</button>
        </div>
      </div>

    </div>
    </>
  );
}
